/*
 * xHarbour build 1.2.1 Intl. (SimpLex) (Rev. 6633)
 * Generated C source code from <S8.prg>
 * Command: S8.prg -n -ic:\ssbuild\xharbour\include;c:\SSBUILD\sslib\include;c:\ssbuild\minigui\include; 
 * Created: 2010.08.09 05:42:40 (Borland C++ 5.5.1 (32 bit))
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "S8.prg"

HB_FUNC( MAIN );
HB_FUNC( STARTSERVER );
HB_FUNC( WIN32EVENTS );
HB_FUNC( R_S8_15SPEED1 );
HB_FUNC( MYADD );
HB_FUNC( MYMAX );
HB_FUNC_INIT( INIT_S8 );


#include "WIN1.xns"
extern HB_NS_WIN1 WIN1;
/* Skipped DEFERRED call to: 'DIVERTCONSTRUCTORCALL' */
HB_FUNC_EXTERN( __MVPUBLIC );
HB_FUNC_EXTERN( SS_NEWSERVER );
HB_FUNC_EXTERN( SS_NEWCIRCUIT );
HB_FUNC_EXTERN( SS_NEWBRANCH );
HB_FUNC_EXTERN( SS_NRESIS );
HB_FUNC_EXTERN( SS_NEWR );
HB_FUNC_EXTERN( SS_ADDRES );
HB_FUNC_EXTERN( SS_CALLR );
HB_FUNC_EXTERN( SS_FIREON );
HB_FUNC_EXTERN( PROCESSMESSAGES );
HB_FUNC_EXTERN( _ISWINDOWDEFINED );
HB_FUNC_EXTERN( _DEFINEWINDOW );
HB_FUNC_EXTERN( _DEFINEIMAGE );
HB_FUNC_EXTERN( _DEFINECHARMASKTEXTBOX );
HB_FUNC_EXTERN( _DEFINEOWNERBUTTON );
HB_FUNC_EXTERN( _DEFINEEDITBOX );
HB_FUNC_EXTERN( _ENDWINDOW );
HB_FUNC_EXTERN( _ACTIVATEWINDOW );
HB_FUNC_EXTERN( GETPROPERTY );
HB_FUNC_EXTERN( STR );
/* Skipped: call to: 'ADDITEM' of: 'WIN1.TEXT1' */
HB_FUNC_EXTERN( MSGBOX );
HB_FUNC_EXTERN( VAL );
HB_FUNC_EXTERN( SS_ON );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 10

#include "hbapi.h"

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_S8 )
{ "DIVERTCONSTRUCTORCALL", {HB_FS_PUBLIC | HB_FS_DEFERRED}, {NULL}, NULL },
{ "MAIN", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MAIN )}, &ModuleFakeDyn },
{ "TRUE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "FALSE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "__MVPUBLIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPUBLIC )}, NULL },
{ "SS_NEWSERVER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_NEWSERVER )}, NULL },
{ "SP1", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP2", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP3", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP4", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP5", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP6", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP7", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SP8", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SS_FLAG3", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SS_FLAG", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SS_FLAG2", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SS_NEWCIRCUIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_NEWCIRCUIT )}, NULL },
{ "SS_NEWBRANCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_NEWBRANCH )}, NULL },
{ "SS_NRESIS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_NRESIS )}, NULL },
{ "SS_NEWR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_NEWR )}, NULL },
{ "SS_ADDRES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_ADDRES )}, NULL },
{ "SS_CALLR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_CALLR )}, NULL },
{ "STARTSERVER", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( STARTSERVER )}, &ModuleFakeDyn },
{ "SS_FIREON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_FIREON )}, NULL },
{ "WIN32EVENTS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( WIN32EVENTS )}, &ModuleFakeDyn },
{ "PROCESSMESSAGES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PROCESSMESSAGES )}, NULL },
{ "R_S8_15SPEED1", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( R_S8_15SPEED1 )}, &ModuleFakeDyn },
{ "_ISWINDOWDEFINED", {HB_FS_PUBLIC}, {HB_FUNCNAME( _ISWINDOWDEFINED )}, NULL },
{ "_DEFINEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DEFINEWINDOW )}, NULL },
{ "_DEFINEIMAGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DEFINEIMAGE )}, NULL },
{ "_DEFINECHARMASKTEXTBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DEFINECHARMASKTEXTBOX )}, NULL },
{ "_DEFINEOWNERBUTTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DEFINEOWNERBUTTON )}, NULL },
{ "MYADD", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( MYADD )}, &ModuleFakeDyn },
{ "MYMAX", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( MYMAX )}, &ModuleFakeDyn },
{ "_DEFINEEDITBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( _DEFINEEDITBOX )}, NULL },
{ "_ENDWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( _ENDWINDOW )}, NULL },
{ "_ACTIVATEWINDOW", {HB_FS_PUBLIC}, {HB_FUNCNAME( _ACTIVATEWINDOW )}, NULL },
{ "GETPROPERTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPROPERTY )}, NULL },
{ "MYTEXT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "ADDITEM", {HB_FS_INDIRECT}, {(PHB_FUNC) &WIN1.TEXT1.ADDITEM}, &ModuleFakeDyn },
{ "MYCOUNT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "MSGBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( MSGBOX )}, NULL },
{ "MYOUT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "VAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( VAL )}, NULL },
{ "X", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "MYITEM", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "INIT_S8$", {HB_FS_INIT | HB_FS_LOCAL}, {HB_INIT_FUNCNAME( INIT_S8 )}, &ModuleFakeDyn },
{ "SS_ON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SS_ON )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_S8 )

#if defined(__ICL)
   #pragma warning(disable:177)
#endif

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_S8
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_S8 )
   #include "hbiniseg.h"
#endif

HB_FUNC( MAIN )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 8,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 18, 0,	/* 18 */
	HB_P_PUSHSYMNEAR, 4,	/* __MVPUBLIC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 2,	/* TRUE */
	HB_P_PUSHSYMNEAR, 3,	/* FALSE */
	HB_P_DOSHORT, 2,
/* 00015 */ HB_P_LINEOFFSET, 1,	/* 19 */
	HB_P_TRUE,
	HB_P_POPVARIABLE, 2, 0,	/* TRUE */
/* 00021 */ HB_P_LINEOFFSET, 2,	/* 20 */
	HB_P_FALSE,
	HB_P_POPVARIABLE, 3, 0,	/* FALSE */
/* 00027 */ HB_P_LINEOFFSET, 3,	/* 21 */
	HB_P_PUSHSYMNEAR, 5,	/* SS_NEWSERVER */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'S', 'e', 'r', 'v', 'e', 'r', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'S', 'l', 'a', 'v', 'e', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'0', '0', '0', 0, 
	HB_P_DOSHORT, 3,
	HB_P_PARAMETER, 6, 0, 1,	/* SP1 */
	HB_P_PARAMETER, 7, 0, 2,	/* SP2 */
	HB_P_PARAMETER, 8, 0, 3,	/* SP3 */
	HB_P_PARAMETER, 9, 0, 4,	/* SP4 */
	HB_P_PARAMETER, 10, 0, 5,	/* SP5 */
	HB_P_PARAMETER, 11, 0, 6,	/* SP6 */
	HB_P_PARAMETER, 12, 0, 7,	/* SP7 */
	HB_P_PARAMETER, 13, 0, 8,	/* SP8 */
/* 00090 */ HB_P_LINEOFFSET, 7,	/* 25 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 14, 0,	/* SS_FLAG3 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 15, 0,	/* SS_FLAG */
	HB_P_ONE,
	HB_P_POPVARIABLE, 16, 0,	/* SS_FLAG2 */
/* 00104 */ HB_P_LINEOFFSET, 8,	/* 26 */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_POPVARIABLE, 15, 0,	/* SS_FLAG */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_POPVARIABLE, 16, 0,	/* SS_FLAG2 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_POPVARIABLE, 14, 0,	/* SS_FLAG3 */
/* 00121 */ HB_P_LINEOFFSET, 9,	/* 27 */
	HB_P_PUSHSYMNEAR, 17,	/* SS_NEWCIRCUIT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'a', 'i', 'n', 0, 
	HB_P_DOSHORT, 1,
/* 00135 */ HB_P_LINEOFFSET, 10,	/* 28 */
	HB_P_PUSHSYMNEAR, 18,	/* SS_NEWBRANCH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'a', 'i', 'n', 0, 
	HB_P_DOSHORT, 1,
/* 00149 */ HB_P_LINEOFFSET, 11,	/* 29 */
	HB_P_PUSHSYMNEAR, 19,	/* SS_NRESIS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'a', 'i', 'n', 0, 
	HB_P_DOSHORT, 1,
/* 00163 */ HB_P_LINEOFFSET, 12,	/* 30 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_POPVARIABLE, 14, 0,	/* SS_FLAG3 */
/* 00170 */ HB_P_LINEOFFSET, 15,	/* 33 */
	HB_P_PUSHSYMNEAR, 20,	/* SS_NEWR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'W', 'I', 'N', '3', '2', 'E', 'V', 'E', 'N', 'T', 'S', '(', ')', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'W', 'I', 'N', '3', '2', 'E', 'V', 'E', 'N', 'T', 'S', 0, 
	HB_P_DOSHORT, 2,
/* 00207 */ HB_P_LINEOFFSET, 17,	/* 35 */
	HB_P_PUSHSYMNEAR, 21,	/* SS_ADDRES */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'W', 'I', 'N', '3', '2', 'E', 'V', 'E', 'N', 'T', 'S', 0, 
	HB_P_DOSHORT, 1,
/* 00228 */ HB_P_LINEOFFSET, 20,	/* 38 */
	HB_P_PUSHSYMNEAR, 20,	/* SS_NEWR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'R', '_', 'S', '8', '_', '1', '5', 's', 'p', 'e', 'e', 'd', '1', '(', ')', 0, 
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	'C', 'i', 'r', 'c', 'u', 'i', 't', 's', 92, 'M', 'a', 'i', 'n', 92, 'M', 'a', 'i', 'n', 92, 'M', 'a', 'i', 'n', 0, 
	HB_P_DOSHORT, 2,
/* 00279 */ HB_P_LINEOFFSET, 23,	/* 41 */
	HB_P_PUSHSYMNEAR, 22,	/* SS_CALLR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	'C', 'i', 'r', 'c', 'u', 'i', 't', 's', 92, 'M', 'a', 'i', 'n', 92, 'M', 'a', 'i', 'n', 92, 'M', 'a', 'i', 'n', 0, 
	HB_P_DOSHORT, 1,
/* 00312 */ HB_P_LINEOFFSET, 24,	/* 42 */
	HB_P_ENDPROC
/* 00315 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( STARTSERVER )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 45, 0,	/* 45 */
	HB_P_PUSHSYMNEAR, 24,	/* SS_FIREON */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00008 */ HB_P_LINEOFFSET, 1,	/* 46 */
	HB_P_ENDPROC
/* 00011 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( WIN32EVENTS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 49, 0,	/* 49 */
	HB_P_PUSHSYMNEAR, 26,	/* PROCESSMESSAGES */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00008 */ HB_P_LINEOFFSET, 1,	/* 50 */
	HB_P_ENDPROC
/* 00011 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( R_S8_15SPEED1 )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 54, 0,	/* 54 */
	HB_P_PUSHSYMNEAR, 28,	/* _ISWINDOWDEFINED */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUE, 13, 2,	/* 525 (abs: 00540) */
/* 00018 */ HB_P_LINEOFFSET, 8,	/* 62 */
	HB_P_PUSHSYMNEAR, 29,	/* _DEFINEWINDOW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 22,	/* 22 */
	202, 205, 207, 237, 207, ' ', 199, 223, 200, 209, ' ', 209, 222, 227, ' ', ' ', ' ', 221, 199, 202, 228, 0, 
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHINT, 218, 1,	/* 474 */
	HB_P_PUSHINT, 121, 1,	/* 377 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 236, 0,	/* 236 */
	HB_P_PUSHINT, 233, 0,	/* 233 */
	HB_P_PUSHINT, 216, 0,	/* 216 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'P', 'W', 'C', 'T', 'I', 'C', 'O', 'N', 0, 
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 53,
/* 00142 */ HB_P_LINEOFFSET, 12,	/* 66 */
	HB_P_PUSHSYMNEAR, 30,	/* _DEFINEIMAGE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 'm', 'a', 'g', 'e', '1', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 240,	/* -16 */
	HB_P_PUSHBYTE, 231,	/* -25 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'W', 'U', '3', '.', 'J', 'P', 'G', 0, 
	HB_P_PUSHINT, 244, 1,	/* 500 */
	HB_P_PUSHINT, 135, 1,	/* 391 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 13,
/* 00185 */ HB_P_LINEOFFSET, 18,	/* 72 */
	HB_P_PUSHSYMNEAR, 31,	/* _DEFINECHARMASKTEXTBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 'x', 't', '1', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 207, 0,	/* 207 */
	HB_P_PUSHBYTE, 116,	/* 116 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHBYTE, 111,	/* 111 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 41,	/* 41 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 255, 0,	/* 255 */
	HB_P_PUSHINT, 207, 0,	/* 207 */
	HB_P_PUSHINT, 185, 0,	/* 185 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 64,	/* 64 */
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 29,
/* 00254 */ HB_P_LINEOFFSET, 25,	/* 79 */
	HB_P_PUSHSYMNEAR, 32,	/* _DEFINEOWNERBUTTON */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'b', 't', 'n', '1', 0, 
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 117,	/* 117 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	199, 207, 206, 199, 225, 0, 
	HB_P_PUSHBLOCK, 13, 0,	/* 13 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 33,	/* MYADD */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHINT, 150, 0,	/* 150 */
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 64,	/* 64 */
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_DOSHORT, 33,
/* 00341 */ HB_P_LINEOFFSET, 32,	/* 86 */
	HB_P_PUSHSYMNEAR, 32,	/* _DEFINEOWNERBUTTON */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'b', 't', 'n', '2', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 145, 0,	/* 145 */
	HB_P_ONE,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	202, 205, 207, 237, 207, ' ', 199, 223, 200, 209, ' ', 209, 222, 227, 0, 
	HB_P_PUSHBLOCK, 13, 0,	/* 13 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 34,	/* MYMAX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHINT, 207, 0,	/* 207 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_DOSHORT, 33,
/* 00437 */ HB_P_LINEOFFSET, 38,	/* 92 */
	HB_P_PUSHSYMNEAR, 35,	/* _DEFINEEDITBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'e', 'd', 'i', 't', '1', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 86, 1,	/* 342 */
	HB_P_PUSHINT, 157, 0,	/* 157 */
	HB_P_PUSHINT, 131, 0,	/* 131 */
	HB_P_PUSHINT, 194, 0,	/* 194 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 255, 0,	/* 255 */
	HB_P_PUSHINT, 215, 0,	/* 215 */
	HB_P_PUSHINT, 174, 0,	/* 174 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 64,	/* 64 */
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 29,
/* 00515 */ HB_P_LINEOFFSET, 39,	/* 93 */
	HB_P_PUSHSYMNEAR, 36,	/* _ENDWINDOW */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00522 */ HB_P_LINEOFFSET, 41,	/* 95 */
	HB_P_PUSHSYMNEAR, 37,	/* _ACTIVATEWINDOW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_DOSHORT, 2,
	HB_P_ENDPROC
/* 00541 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( MYADD )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 99, 0,	/* 99 */
	HB_P_PUSHSYMNEAR, 38,	/* GETPROPERTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 'x', 't', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'V', 'a', 'l', 'u', 'e', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPVARIABLE, 39, 0,	/* MYTEXT */
/* 00034 */ HB_P_LINEOFFSET, 1,	/* 100 */
	HB_P_PUSHSYMNEAR, 40,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 39, 0,	/* MYTEXT */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 39, 0,	/* MYTEXT */
/* 00047 */ HB_P_LINEOFFSET, 2,	/* 101 */
	HB_P_PUSHSYMNEAR, 41,	/* ADDITEM */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00054 */ HB_P_LINEOFFSET, 3,	/* 102 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00059 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( MYMAX )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 104, 0,	/* 104 */
	HB_P_PUSHSYMNEAR, 38,	/* GETPROPERTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'l', 'i', 's', 't', '1', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'I', 't', 'e', 'm', 'C', 'o', 'u', 'n', 't', 0, 
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPVARIABLE, 42, 0,	/* MYCOUNT */
/* 00038 */ HB_P_LINEOFFSET, 1,	/* 105 */
	HB_P_PUSHVARIABLE, 42, 0,	/* MYCOUNT */
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 50,	/* 50 (abs: 00095) */
/* 00047 */ HB_P_LINEOFFSET, 2,	/* 106 */
	HB_P_PUSHSYMNEAR, 43,	/* MSGBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	199, 225, 222, 199, 198, 227, 201, ' ', 202, 206, 225, 230, ' ', 227, 228, ' ', 199, 225, 199, 218, 207, 199, 207, 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	218, 221, 230, 199, 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 44, 0,	/* MYOUT */
/* 00090 */ HB_P_LINEOFFSET, 3,	/* 107 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00095 */ HB_P_LINEOFFSET, 5,	/* 109 */
	HB_P_PUSHSYMNEAR, 38,	/* GETPROPERTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'l', 'i', 's', 't', '1', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'i', 't', 'e', 'm', 0, 
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPVARIABLE, 34, 0,	/* MYMAX */
/* 00128 */ HB_P_LINEOFFSET, 6,	/* 110 */
	HB_P_PUSHVARIABLE, 42, 0,	/* MYCOUNT */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 00166) */
/* 00137 */ HB_P_LINEOFFSET, 7,	/* 111 */
	HB_P_PUSHSYMNEAR, 43,	/* MSGBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 34, 0,	/* MYMAX */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	199, 223, 200, 209, ' ', 209, 222, 227, 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 44, 0,	/* MYOUT */
/* 00161 */ HB_P_LINEOFFSET, 8,	/* 112 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00166 */ HB_P_LINEOFFSET, 10,	/* 114 */
	HB_P_PUSHSYMNEAR, 45,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 34, 0,	/* MYMAX */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 34, 0,	/* MYMAX */
/* 00179 */ HB_P_LINEOFFSET, 11,	/* 115 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_POPVARIABLE, 46, 0,	/* X */
	HB_P_PUSHVARIABLE, 46, 0,	/* X */
	HB_P_PUSHVARIABLE, 42, 0,	/* MYCOUNT */
	HB_P_ONE,
	HB_P_FORTEST,
	HB_P_JUMPFALSENEAR, 82,	/* 82 (abs: 00276) */
/* 00196 */ HB_P_LINEOFFSET, 12,	/* 116 */
	HB_P_PUSHSYMNEAR, 38,	/* GETPROPERTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'w', 'i', 'n', '1', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'l', 'i', 's', 't', '1', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'i', 't', 'e', 'm', 0, 
	HB_P_PUSHVARIABLE, 46, 0,	/* X */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPVARIABLE, 47, 0,	/* MYITEM */
/* 00231 */ HB_P_LINEOFFSET, 13,	/* 117 */
	HB_P_PUSHSYMNEAR, 45,	/* VAL */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 47, 0,	/* MYITEM */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 47, 0,	/* MYITEM */
/* 00244 */ HB_P_LINEOFFSET, 14,	/* 118 */
	HB_P_PUSHVARIABLE, 47, 0,	/* MYITEM */
	HB_P_PUSHVARIABLE, 34, 0,	/* MYMAX */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00263) */
/* 00255 */ HB_P_LINEOFFSET, 15,	/* 119 */
	HB_P_PUSHVARIABLE, 47, 0,	/* MYITEM */
	HB_P_POPVARIABLE, 34, 0,	/* MYMAX */
/* 00263 */ HB_P_LINEOFFSET, 17,	/* 121 */
	HB_P_PUSHVARIABLE, 46, 0,	/* X */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_POPVARIABLE, 46, 0,	/* X */
	HB_P_JUMPNEAR, 168,	/* -88 (abs: 00186) */
/* 00276 */ HB_P_LINEOFFSET, 18,	/* 122 */
	HB_P_PUSHSYMNEAR, 40,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 34, 0,	/* MYMAX */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 34, 0,	/* MYMAX */
/* 00289 */ HB_P_LINEOFFSET, 19,	/* 123 */
	HB_P_PUSHSYMNEAR, 43,	/* MSGBOX */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 34, 0,	/* MYMAX */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	199, 223, 200, 209, ' ', 209, 222, 227, 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 44, 0,	/* MYOUT */
/* 00313 */ HB_P_LINEOFFSET, 20,	/* 124 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00318 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_INIT( INIT_S8 )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 130, 0,	/* 130 */
	HB_P_PUSHSYMNEAR, 49,	/* SS_ON */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00008 */ HB_P_LINEOFFSET, 1,	/* 131 */
	HB_P_ENDPROC
/* 00011 */
   };

   hb_vmExecute( pcode, symbols );
}

