DEFINE CLASS TR_CHECKBOX AS CHECKBOX
PROCEDURE LOSTFOCUS
APPLICATION.ActiveForm.REFRESH
RETURN

PROCEDURE KEYPRESS
LPARAMETERS nKeyCode, nShiftAltCtrl
IF NKEYCODE = 23 && CTRL+W
   THIS.Parent.Parent.Parent.Parent.KEYPRESS(nKeyCode, nShiftAltCtrl)
ENDIF
RETURN
ENDDEFINE
